### ISSUE TITLE
Updated Working Practices prose

### ISSUE THREAD

**Issue by erwilliamson** [SAS-DHRH/dhcc-toolkit#3]
Hi all, while streamlining the prose in the Working Practices doc, I’ve removed the following paragraph – are people happy with this? Shout if not and it can be put back. It feels like a bit of a tangent to go from advising on device usage to thinking about moving countries - perhaps a bit outside our scope, though if someone had somewhere else to put this they could do so.

‘Note that every digital device uses electricity. The amount of CO2 that is used by producing the electricity depends on the way of production. Every country uses different ways to produce electricity (f.e. Fossil fuels [bad for the climate], nuclear power [bad for the environment, bad for climate and dangerous], renewables [best to stop climate crisis], Therefore, the amount of CO2 used depends on the country you live in. If you would like to think about moving into another country, you can find information about the ways of electricity-production per country here: https://ourworldindata.org/electricity-mix .'

Hopefully the changes I just committed went through ok, too...

**Comment by martysteer** [comment]
Makes sense to me. Changes have gone through to the site too.

**Comment by franciscrot** [comment]
I think this is a good edit. (There is maybe an interesting point about energy coming from the grid, and therefore just using whatever energy mix is supplied to the grid - people may be under the impression that using a renewable supplier literally means that the literal energy you are using is generated by wind solar etc., rather than just pushing the overall energy supply in the right direction. But maybe we leave it for now!)
