### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by franciscrot** [SAS-DHRH/dhcc-toolkit#9]
I will leave it for a bit, but I think before 10 November we should change the very front page, so that it leads with an explanation of what this is and who it's for?

https://sas-dhrh.github.io/dhcc-toolkit/

(Any thoughts on what it should / shouldn't say?)

**Comment by erwilliamson** [comment]
I think this is a good idea, though it's worth keeping it brief because there's a fuller explanation on the Introduction page - perhaps just a sentence or two? 
Something like: 'This toolkit is a guide to making your research practices more environmentally responsible. It is geared both towards digital practices and more general approaches, from advocacy to travel, and we hope it will be relevant to researchers, educators, students, administrators, librarians, technicians, and others. It is a community-developed work-in-progress, and you are warmly invited to contribute.' Or shift emphasis more to digital/dh practices?

**Comment by franciscrot** [comment]
Sounds perfect to me
